// ============================================================
// PART DATABASE — Simulated ML knowledge base
// ============================================================
const PARTS = {
  shaft: {
    name: 'Main Shaft',
    type: 'Rotating Component',
    material: 'Steel 4140',
    standard: 'ISO 286-1',
    dims: {length:'460 mm', diameter:'Ø80 mm', tolerance:'h6'},
    finish: 'Ra 1.6 μm',
    hardness: '28-32 HRC',
    function: 'Primary torque transmission',
    assembly: 'Press fit into bearings',
    related: ['lbearing','rbearing','gear','keyway'],
    conf: {yolo:0.97, resnet:0.95, cluster:0.89},
    color:'#00e5ff', bom:1, qty:1,
  },
  lbearing: {
    name: 'Left Bearing Housing',
    type: 'Bearing Assembly',
    material: 'Cast Iron GG25',
    standard: 'ISO 15 (6316)',
    dims:{bore:'Ø80 mm', OD:'Ø140 mm', width:'55 mm'},
    load:'Radial + Axial',
    rpm:'Max 3200 RPM',
    function: 'Supports shaft radially',
    related:['shaft','flangeL','sealL'],
    conf:{yolo:0.93, resnet:0.91, cluster:0.84},
    color:'#7c3aed', bom:2, qty:1,
  },
  rbearing: {
    name: 'Right Bearing Housing',
    type: 'Bearing Assembly',
    material: 'Cast Iron GG25',
    standard: 'ISO 15 (6316)',
    dims:{bore:'Ø80 mm', OD:'Ø140 mm', width:'55 mm'},
    load:'Radial only',
    rpm:'Max 3200 RPM',
    function: 'Floating end bearing',
    related:['shaft','flangeR','sealR'],
    conf:{yolo:0.93, resnet:0.90, cluster:0.83},
    color:'#7c3aed', bom:3, qty:1,
  },
  gear: {
    name: 'Spur Gear',
    type: 'Power Transmission',
    material: 'Steel 20MnCr5',
    standard: 'DIN 3962',
    dims:{PCD:'Ø140 mm', module:'2.5', teeth:'56', faceWidth:'40 mm'},
    finish: 'Ra 0.8 μm',
    function: 'Speed/torque conversion',
    related:['shaft','keyway','bolt'],
    conf:{yolo:0.96, resnet:0.94, cluster:0.88},
    color:'#f59e0b', bom:4, qty:1,
  },
  keyway: {
    name: 'Keyway Slot',
    type: 'Mechanical Feature',
    material: 'Same as shaft',
    standard: 'ISO 773',
    dims:{width:'20 mm', depth:'12 mm', length:'60 mm'},
    function: 'Gear-to-shaft torque lock',
    related:['shaft','gear'],
    conf:{yolo:0.88, resnet:0.85, cluster:0.79},
    color:'#10b981', bom:5, qty:1,
  },
  bolt: {
    name: 'M16 Hex Bolt',
    type: 'Fastener',
    material: 'Alloy Steel 10.9',
    standard: 'ISO 4014',
    dims:{thread:'M16×2.0', length:'40 mm', head:'24 mm'},
    torque:'195 Nm',
    function: 'Gear-plate fastening',
    related:['gear','shaft'],
    conf:{yolo:0.91, resnet:0.89, cluster:0.82},
    color:'#ef4444', bom:6, qty:4,
  },
  flangeL: {
    name: 'Left Shaft Collar',
    type: 'Retention Component',
    material: 'Steel 1045',
    standard: 'Custom',
    dims:{OD:'Ø120 mm', bore:'Ø80 mm', width:'30 mm'},
    function: 'Axial bearing retention',
    related:['shaft','lbearing'],
    conf:{yolo:0.87, resnet:0.85, cluster:0.78},
    color:'#10b981', bom:7, qty:1,
  },
  flangeR: {
    name: 'Right Shaft Collar',
    type: 'Retention Component',
    material: 'Steel 1045',
    standard: 'Custom',
    dims:{OD:'Ø120 mm', bore:'Ø80 mm', width:'30 mm'},
    function: 'Floating end retention',
    related:['shaft','rbearing'],
    conf:{yolo:0.87, resnet:0.84, cluster:0.77},
    color:'#10b981', bom:8, qty:1,
  },
  lbearingjournal: {
    name: 'Left Journal Zone',
    type: 'Shaft Feature',
    material: 'Steel 4140 (ground)',
    standard: 'ISO 286-1',
    dims:{diameter:'Ø80 h6', length:'60 mm'},
    finish: 'Ra 0.4 μm',
    function: 'Bearing seating surface',
    related:['shaft','lbearing'],
    conf:{yolo:0.90, resnet:0.88, cluster:0.81},
    color:'#00e5ff', bom:null, qty:null,
  },
  rbearingjournal: {
    name: 'Right Journal Zone',
    type: 'Shaft Feature',
    material: 'Steel 4140 (ground)',
    standard: 'ISO 286-1',
    dims:{diameter:'Ø80 h6', length:'60 mm'},
    finish: 'Ra 0.4 μm',
    function: 'Bearing seating surface',
    related:['shaft','rbearing'],
    conf:{yolo:0.90, resnet:0.87, cluster:0.80},
    color:'#00e5ff', bom:null, qty:null,
  },
  sealL: {
    name: 'Left Seal Groove',
    type: 'Sealing Feature',
    material: 'Machined in shaft',
    standard: 'DIN 471',
    dims:{width:'8 mm', depth:'3 mm'},
    function: 'O-ring / lip seal seat',
    related:['shaft','lbearing','flangeL'],
    conf:{yolo:0.82, resnet:0.80, cluster:0.74},
    color:'#f59e0b', bom:null, qty:null,
  },
  sealR: {
    name: 'Right Seal Groove',
    type: 'Sealing Feature',
    material: 'Machined in shaft',
    standard: 'DIN 471',
    dims:{width:'8 mm', depth:'3 mm'},
    function: 'O-ring / lip seal seat',
    related:['shaft','rbearing','flangeR'],
    conf:{yolo:0.82, resnet:0.79, cluster:0.73},
    color:'#f59e0b', bom:null, qty:null,
  },
  threadL: {
    name: 'Left Thread End',
    type: 'Threaded Feature',
    material: 'Steel 4140',
    standard: 'ISO 965-1',
    dims:{thread:'M80×2.0', length:'42 mm', class:'6g'},
    function: 'Lock nut retention',
    related:['shaft'],
    conf:{yolo:0.86, resnet:0.84, cluster:0.76},
    color:'#ef4444', bom:9, qty:1,
  },
  threadR: {
    name: 'Right Thread End',
    type: 'Threaded Feature',
    material: 'Steel 4140',
    standard: 'ISO 965-1',
    dims:{thread:'M80×2.0', length:'42 mm', class:'6g'},
    function: 'Drive coupling end',
    related:['shaft'],
    conf:{yolo:0.86, resnet:0.83, cluster:0.76},
    color:'#ef4444', bom:10, qty:1,
  },
};

// ============================================================
// BOM DATA
// ============================================================
const BOM = [
  {num:1, name:'Main Shaft', mat:'Steel 4140', qty:'1 pc', color:'#00e5ff'},
  {num:2, name:'Bearing Housing (L)', mat:'GG25', qty:'1 pc', color:'#7c3aed'},
  {num:3, name:'Bearing Housing (R)', mat:'GG25', qty:'1 pc', color:'#7c3aed'},
  {num:4, name:'Spur Gear M2.5 Z56', mat:'20MnCr5', qty:'1 pc', color:'#f59e0b'},
  {num:5, name:'Keyway Key', mat:'Steel C45', qty:'1 pc', color:'#10b981'},
  {num:6, name:'Hex Bolt M16×40', mat:'10.9 Alloy', qty:'4 pc', color:'#ef4444'},
  {num:7, name:'Shaft Collar (L)', mat:'Steel 1045', qty:'1 pc', color:'#10b981'},
  {num:8, name:'Shaft Collar (R)', mat:'Steel 1045', qty:'1 pc', color:'#10b981'},
  {num:9, name:'Lock Nut M80 (L)', mat:'Steel 8.8', qty:'1 pc', color:'#ef4444'},
  {num:10, name:'Drive End Cap (R)', mat:'Alu 6082', qty:'1 pc', color:'#ef4444'},
];

// ============================================================
// ML LOG
// ============================================================
const ML_LOG = [
  {time:'00:00', msg:'Drawing loaded — preprocessing started', tag:'SYS', color:'#8892a4'},
  {time:'00:02', msg:'Raster-to-vector conversion complete', tag:'PRE', color:'#8892a4'},
  {time:'00:03', msg:'YOLOv8: 13 bounding boxes detected', tag:'SUP', color:'#00e5ff'},
  {time:'00:04', msg:'ResNet classifier: 13/13 parts classified', tag:'SUP', color:'#00e5ff'},
  {time:'00:05', msg:'OCR: 8 dimension strings extracted', tag:'SUP', color:'#00e5ff'},
  {time:'00:06', msg:'DBSCAN: 4 feature clusters formed', tag:'UNS', color:'#7c3aed'},
  {time:'00:07', msg:'AutoEncoder: no anomalies detected (score 0.04)', tag:'UNS', color:'#7c3aed'},
  {time:'00:08', msg:'GNN: 18 part-relationships mapped', tag:'GNN', color:'#10b981'},
  {time:'00:09', msg:'EWC: weights preserved from previous session', tag:'SLF', color:'#f59e0b'},
  {time:'00:10', msg:'Fusion model: confidence score 88%', tag:'FUS', color:'#10b981'},
  {time:'00:11', msg:'Active learning: 2 low-confidence regions flagged', tag:'SLF', color:'#f59e0b'},
  {time:'00:12', msg:'Knowledge graph updated with 23 nodes', tag:'GNN', color:'#10b981'},
];

// ============================================================
// STATE
// ============================================================
let selectedPart = null;
let feedbackCount = 0;
let currentTab = 'info';
let zoomLevel = 1;
let currentTool = 'select';
let hasScanned = true;
